### ISSUE TITLE
v0.0.2-hotfix1 sequencer storing tx issue

### ISSUE THREAD

**Issue by Annihilatopia** [0xPolygon/cdk-validium-node#65]
Hey there,

After changing to v0.0.2-hotfix1 the maxFeePerDataGas issue is resolved, however, when performing a transaction on l2, the sequencer crashes when trying to store the tx

```
2024-02-01T04:37:47.798Z        DEBUG   sequencer/dbmanager.go:172      Storing tx 0x0ec1d4c9cd53b8581863877caea32d0f1cd0470a675806c446f41ee1ac7e1d78   {"pid": 7, "version": "v0.0.2-hotfix1"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf58240]

goroutine 209 [running]:
github.com/ethereum/go-ethereum/trie.(*StackTrie).hash(0xc00061aeb0, 0xc0006435c0, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.11/trie/stacktrie.go:413 +0x3a0
github.com/ethereum/go-ethereum/trie.(*StackTrie).Hash(0xc0002a0700?)
        /go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.11/trie/stacktrie.go:468 +0x39
github.com/ethereum/go-ethereum/core/types.DeriveSha({0x1bfdba0, 0xc00081b920}, {0x1c00710, 0xc00061aeb0})
        /go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.11/core/types/hashing.go:133 +0x37f
github.com/ethereum/go-ethereum/core/types.NewBlock(0x868de7d531c0b178?, {0xc00064c388?, 0x1, 0x1}, {0x28c1220, 0x0, 0x0}, {0xc00064c390, 0x1, 0x1}, ...)
        /go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.11/core/types/block.go:230 +0x119
github.com/0xPolygon/cdk-validium-node/state.(*State).StoreTransaction(0xc0006d2000, {0x1c04e38, 0xc00004e040}, 0x4e?, 0xc000704b40, {0x78, 0xa1, 0x6, 0x22, 0x39, ...}, ...)
        /src/state/transaction.go:933 +0x4c5
github.com/0xPolygon/cdk-validium-node/sequencer.(*dbManager).StoreProcessedTxAndDeleteFromPool(0xc0006cc140, {0x1c04e38, 0xc00004e040}, {{0xe, 0xc1, 0xd4, 0xc9, 0xcd, 0x53, 0xb8, ...}, ...})
        /src/sequencer/dbmanager.go:178 +0x172
github.com/0xPolygon/cdk-validium-node/sequencer.(*finalizer).storeProcessedTx(0xc000966300, {0x1c04e38, 0xc00004e040}, {{0xe, 0xc1, 0xd4, 0xc9, 0xcd, 0x53, 0xb8, ...}, ...})
        /src/sequencer/finalizer.go:782 +0x14c
github.com/0xPolygon/cdk-validium-node/sequencer.(*finalizer).storePendingTransactions(0xc000966300, {0x1c04e38, 0xc00004e040})
        /src/sequencer/finalizer.go:216 +0x270
created by github.com/0xPolygon/cdk-validium-node/sequencer.(*finalizer).Start
        /src/sequencer/finalizer.go:187 +0x2e5
```

**Comment by deepalIGD** [comment]
Hi @Annihilatopia Could you please let us know what was the "maxFeePerDataGas" issue that you faced and for which version of the code did this issue occur?

**Comment by Annihilatopia** [comment]
It was an issue related to Dencun fork, using the hotfix versions resolved the issue.
